MarketingNotifications.Web/ViewModels/NotificationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.UI;
using System.Web.UI.WebControls;
using MarketingNotifications.Web.Models;

namespace MarketingNotifications.Web.ViewModels
{
    public class NotificationViewModel
    {
        [Required]
        [DataType(DataType.MultilineText)]
        [StringLength(160, ErrorMessage = "Text shoudln't be longer than 160 characters.")]
        public string Message { get; set; }

        [Display(Name = "Image URL")]
        public string ImageUrl { get; set; }

        [Display(Name = "RV Show Subscribers")]
        public bool Rv { get; set; }

        [Display(Name = "Boat Show Subscribers")]
        public bool Boat { get; set; }

        [Display(Name = "Bridal Show Subscribers")]
        public bool Bridal { get; set; }

        [Display(Name = "Test Group - Office Numbers")]
        public bool TestGroup { get; set; }
    }
}

MarketingNotifications.Web/Controllers/NotificationsController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MarketingNotifications.Web.Domain;
using MarketingNotifications.Web.Migrations;
using MarketingNotifications.Web.Models.Repository;
using MarketingNotifications.Web.ViewModels;

namespace MarketingNotifications.Web.Controllers
{
    public class NotificationsController : Controller
    {
        private readonly ISubscribersRepository _repository;
        private readonly IMessageSender _messageSender;

        public NotificationsController() : this(new SubscribersRepository(), new MessageSender())
        {
        }

        public NotificationsController(ISubscribersRepository repository, IMessageSender messageSender)
        {
            using (var context = new MarketingNotificationsContext())
            {
                ViewBag.CountBoat = context.Subscribers.Count(s => s.Boat && s.Subscribed);
                ViewBag.CountRV = context.Subscribers.Count(s => s.Rv && s.Subscribed);
                ViewBag.CountBridal = context.Subscribers.Count(s => s.Bridal && s.Subscribed);
                ViewBag.CountTest = context.Subscribers.Count(s => s.TestGroup && s.Subscribed);
                ViewBag.CountNonSub = context.Subscribers.Count(s => !s.Subscribed);
                ViewBag.CountSub = context.Subscribers.Count(s => s.Subscribed);

                ViewBag.BoatCost = (context.Subscribers.Count(s => s.Boat && s.Subscribed))*.0075;
                ViewBag.RvCost = (context.Subscribers.Count(s => s.Rv && s.Subscribed))*.0075;
                ViewBag.BridalCost = (context.Subscribers.Count(s => s.Bridal && s.Subscribed))*.0075;
                ViewBag.TestCost = (context.Subscribers.Count(s => s.TestGroup && s.Subscribed))*.0075;
            }
            _messageSender = messageSender;
            _repository = repository;
        }

        // GET: Notifications/Create
        public ActionResult Create()
        {
            return View();
        }
        
        // POST: Notifications/Create
        [HttpPost]
        public async Task<ActionResult> Create(NotificationViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Original code - Use this to send to ALL subscribers
                /*
                var subscribers = await _repository.FindActiveSubscribersAsync();
                subscribers.ForEach(subscriber =>
                {
                    _messageSender.Send(
                        subscriber.PhoneNumber,
                        model.Message,
                        model.ImageUrl);
                });

                ModelState.Clear();
                ViewBag.FlashMessage = "Messages on their way to RV Subscribers!";
                */

                

                if (!model.Rv && !model.Boat && !model.Bridal && !model.TestGroup)
                {
                    ViewBag.FlashMessage = "Please select a list.";
                }

                // sends to RV group only if RV group is ticked
                else if (model.Rv)
                {
                    var subscribers = await _repository.FindActiveRvListSubscribersAsync();
                    subscribers.ForEach(subscriber =>
                    {
                        _messageSender.Send(
                            subscriber.PhoneNumber,
                            model.Message,
                            model.ImageUrl);
                    });

                    ModelState.Clear();
                    ViewBag.FlashMessage = "Messages on their way to RV Subscribers!";
                }

                // sends to Boat group only if Boat checkbox is ticked
                else if (model.Boat)
                {
                    var subscribers = await _repository.FindActiveBoatListSubscribersAsync();
                    subscribers.ForEach(subscriber =>
                    {
                        _messageSender.Send(
                            subscriber.PhoneNumber,
                            model.Message,
                            model.ImageUrl);
                    });

                    ModelState.Clear();
                    ViewBag.FlashMessage = "Messages on their way to Boat Subscribers!";
                }

                //Sends to Bridal group only if Bridal group is ticked
                else if (model.Bridal)
                {
                    var subscribers = await _repository.FindActiveBridalListSubscribersAsync();
                    subscribers.ForEach(subscriber =>
                    {
                        _messageSender.Send(
                            subscriber.PhoneNumber,
                            model.Message,
                            model.ImageUrl);
                    });

                    ModelState.Clear();
                    ViewBag.FlashMessage = "Messages on their way to Bridal Subscribers!";
                }

                // Sends to Test Group only if Test Group checkbox is ticked.
                else if (model.TestGroup)
                {
                    var subscribers = await _repository.FindActiveTestListSubscribersAsync();
                    subscribers.ForEach(subscriber =>
                    {
                        _messageSender.Send(
                            subscriber.PhoneNumber,
                            model.Message,
                            model.ImageUrl);
                    });

                    ModelState.Clear();
                    ViewBag.FlashMessage = "Messages on their way to TEST Group Subscribers!";
                }
                
                return View();
            }

            return View(model);
        }
    }
}

MarketingNotifications.Web/Views/Notifications/Create.cshtml
@model MarketingNotifications.Web.ViewModels.NotificationViewModel
<h1>Greenband SMS Marketing Form</h1>
<p>Use this form to send MMS notifications to any subscribers.</p>
<p>You may only send to 1 list at a time.</p>
@using (Html.BeginForm("Create", "Notifications"))
{
    <div class="form-group">
        @Html.CheckBoxFor(m => m.TestGroup)
        @Html.LabelFor(m => m.TestGroup): @ViewBag.CountTest <i>($@ViewBag.TestCost)</i>
        <br />
        @Html.CheckBoxFor(m => m.Rv)
        @Html.LabelFor(m => m.Rv): @ViewBag.CountRv <i>($@ViewBag.RvCost)</i>
        <br />
        @Html.CheckBoxFor(m => m.Boat)
        @Html.LabelFor(m => m.Boat): @ViewBag.CountBoat <i>($@ViewBag.BoatCost)</i>
        @*        <label>Boat Subscribers:</label> *@
        <br />
        @Html.CheckBoxFor(m => m.Bridal)
        @Html.LabelFor(m => m.Bridal): @ViewBag.CountBridal <i>($@ViewBag.BridalCost)</i>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Message)
        <br />
        @Html.EditorFor(m => m.Message, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Text Message Here", @maxLength = "160" } })
        @*        @Html.TextBoxFor(m => m.Message, new { @class = "form-control headline", placeholder = "Enter Text Message here.", maxlength = "150"})*@
        @Html.ValidationMessageFor(x => x.Message, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ImageUrl)
        @Html.TextBoxFor(m => m.ImageUrl, new { @class = "form-control", placeholder = "http://fake.twilio.com/some_image.png" })
    </div>
    <button type="submit" class="btn btn-primary">Send Message</button>
    <div>
        <br />
        Total Subscribers: @ViewBag.CountSub
        <br/>
        Total Unsubscribed: @ViewBag.CountNonSub
    </div>
}